website/routes/admin_views.py
#libraries needed
from flask import (
    Blueprint, 
    render_template, 
    request, 
    redirect, 
    url_for, 
    flash,
    jsonify
)
from flask_login import (
                        LoginManager,
                         login_user,
                         logout_user,
                         login_required,
                         current_user
                         )


from website import db
from website.models.database_models import Games, Links
from website.security.limiter import limiter 

admin_views = Blueprint('admin_views', __name__)

#add GAMES
@admin_views.route('/add_games', methods=['GET', 'POST'])
@limiter.limit("100 per minute")
@login_required
def add_games():
    if request.method == 'POST':
        try:
            game_name = request.form.get('gamename')
            existing_game = Games.query.filter_by(game_name=game_name).first()
            if existing_game:
                flash('Game with this name already exists', category='manage_games_error')
            else:
                game = Games(game_name=game_name)
                db.session.add(game)
                db.session.commit()
                flash('Game created successfully', category='manage_games_success')
        except Exception as e:
            flash(str(e), category='manage_games_error')

    games = Games.query.all()

    return render_template('admin_manage_game.html', games=games)


#update games
@admin_views.route('/update_game', methods=['POST'])
@limiter.limit("100 per minute")
@login_required
def update_game():
    if request.method == 'POST':
        try:
            game_id = request.form.get('updateGameId')
            new_game_name = request.form.get('updateGameName')
            
            if not new_game_name.strip():
                return jsonify({'error': 'Game name cannot be empty'}), 400
            
            game = Games.query.get(game_id)
            if game:
                # Check if a game with the new name already exists
                existing_game = Games.query.filter_by(game_name=new_game_name).first()
                if existing_game and existing_game.id != game_id:
                    return jsonify({'error': 'Game with that name already exists'}), 400
                
                game.game_name = new_game_name
                db.session.commit()
                return jsonify({'message': 'Game updated successfully'})
            else:
                return jsonify({'error': 'Game not found'}), 404

        except Exception as e:
            return jsonify({'error': str(e)}), 500

#DELETE GAMES
@admin_views.route('/delete_game/<int:game_id>', methods=['POST'])
@limiter.limit("100 per minute")
@login_required
def delete_game(game_id):
    if request.method == 'POST':
        try:
            game = Games.query.get(game_id)
            Links.query.filter_by(game_id=game.id).delete()
            db.session.delete(game)
            db.session.commit()
            flash('Game deleted successfully', 'manage_games_success')
            return redirect(url_for('admin_views.add_games'))
        except Exception as e:
            flash(str(e), category='manage_games_error')
            
    games = Games.query.all()
    return redirect(url_for('admin_views.add_games',games=games))


#ADD LINKS
@admin_views.route('/add_links/<int:game_id>', methods=['GET', 'POST'])
@limiter.limit("100 per minute")
@login_required
def add_links(game_id):
    game = Games.query.get(game_id)

    if request.method == 'POST':
        try:
            links = request.form.get('link')
            existing_link = Links.query.filter_by(game_id=game_id, url=links).first()
            if existing_link:
                flash('link already exists for this game', category='manage_links_error') 
            else:               
                link = Links(game_id=game.id, url=links)
                db.session.add(link)
                db.session.commit()
                flash('Game Link added successfully', category='manage_links_success')
        except Exception as e:
            flash(str(e), category='manage_links_error')
 
    return render_template('admin_manage_link.html', game=game, links=game.links)


# Update LINKS
@admin_views.route('/update_link/<int:link_id>', methods=['POST'])
@limiter.limit("100 per minute")
@login_required
def update_link(link_id):
    if request.method == 'POST':
        try:
            new_link = request.form.get('updateLink')
            if not new_link.strip():
                return jsonify({'error': 'Link cannot be empty'}), 400

            link = Links.query.get(link_id)
            if link:
                existing_link = Links.query.filter_by(game_id=link.game_id, url=new_link).first()
                if existing_link and existing_link.id != link_id:
                    return jsonify({'error': 'Link already exists for this game'}), 400

                link.url = new_link
                db.session.commit()
                return jsonify({'message': 'Link updated successfully'})
            else:
                return jsonify({'error': 'Link not found'}), 404

        except Exception as e:
            return jsonify({'error': str(e)}), 500


#delete LINKS
@admin_views.route('/delete_links/<int:link_id>', methods=['POST'])
@limiter.limit("100 per minute")
@login_required
def delete_links(link_id):
    link = Links.query.get(link_id)
    if request.method == 'POST':
        if link is None:
            flash('Link not found', category='manage_links_error')
            return redirect(url_for('admin_views.add_links'))

        if request.method == 'POST':
            try:
                db.session.delete(link)
                db.session.commit()
                flash('Link deleted successfully', category='manage_links_success')
            except Exception as e:
                flash(str(e), category='manage_links_error')

    return redirect(url_for('admin_views.add_links', game_id=link.game_id))
#

website/routes/public_views.py
#libraries needed
from flask import (
    Blueprint, 
    render_template, 
    request, 
    redirect, 
    url_for, 
    flash
)
from flask_login import (
                        LoginManager,
                         login_user,
                         logout_user,
                         login_required,
                         current_user
                         )

from website.models.database_models import Games,Links
from website.security.limiter import limiter 

public_views = Blueprint('public_views', __name__)

@public_views.route('/', methods=['GET', 'POST'])
@limiter.limit("100 per minute")
def home():
    games = Games.query.all()
    games = sorted(games, key=lambda x: x.game_name.lower())
    return render_template('home.html', games=games)

@public_views.route('/about', methods=['GET', 'POST'])
@limiter.limit("100 per minute")
def about():
    return render_template('about.html')

website/templates/about.html
{% extends 'public_base_top_nav.html' %}
{% block title %}
    ABOUT
{% endblock %}

{% block content %}

  <div class="container mt-5">
    <h1 class="text-center mb-4">About Our Website</h1>
    <div class="card">
      <div class="card-body">
        <p class="card-text">Welcome to our website! We're passionate about preserving 3DS games for future generations. While we don't own the ROMs, we've curated a collection for you to enjoy. Our goal is to provide a safe and easy way to access these games. Thank you for supporting our mission!</p>
      </div>
    </div>
    <div class="mt-4">
        <h3 class="text-center">Follow Us</h3>
        <div class="d-flex justify-content-center mt-3">
          <a href="https://web.facebook.com/aldrich.panio" class="btn btn-primary me-2" target="_blank"><i class="fab fa-facebook"></i></a>
          <a href="https://github.com/Ion213" class="btn btn-dark" target="_blank"><i class="fab fa-github"></i></a>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.4.0/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

website/templates/admin_base_top_nav.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>          
    {% block title %}
    {% endblock %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><h1>ADMIN DASHBOARD</h1></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                  <a href="{{ url_for('admin_views.add_games') }}" class="nav-link"><i class="fas fa-gamepad"></i> MANAGE GAMES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick="confirmLogout()"><i class="fas fa-sign-out-alt"></i> LOG_OUT</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


    {% block content %}
    {% endblock %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    function confirmLogout() {
      if (confirm("Are you sure you want to logout?")) {
          window.location.href = "{{ url_for('admin_auth.admin_logout') }}";
      }
    }
  </script>
</body>

</html>

website/templates/admin_login.html
{% extends 'public_base_top_nav.html' %}

{% block title %}
    LOGIN
{% endblock %}

{% block content %}

<div>
    <!-- jinjacode flash message form flask-->
    {% with messages = get_flashed_messages(with_categories=true)%}
        {%if messages%}
            {%for category, message in messages%}
            <!-- sweet alert error-->
                {%if category =='login_error'%}
                    <div id="myAlert" class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="close" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                <!-- sweet alert success-->
                {%else%}
                <div id="myAlert" class="alert alert-success alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="close" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                {%endif%}
            {%endfor%}
        {%endif%}
    {% endwith %}
    </div>
    
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">ADMIN LOGIN</div>
                    <div class="card-body">

                        <form method="POST">
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
                            </div>
                            <br/>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        //id only can enter number script
        function filterNonNumeric(event) {
            var charCode = event.keyCode || event.which;
            if (charCode > 31 && (charCode < 48 || charCode > 57)) {
                event.preventDefault();
            }
        }
         //SWEET ALERT script
        document.addEventListener('DOMContentLoaded', function () {
            var closeButton = document.querySelector('#myAlert .close');
            closeButton.addEventListener('click', function () {
                var alert = document.querySelector('#myAlert');
                alert.remove();
            });
        });
    
     //hide and unhide password
        document.getElementById('showPasswordBtn').addEventListener('click', function () {
            var passwordInput = document.getElementById('password');
            var type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordInput.setAttribute('type', type);
            this.querySelector('i').classList.toggle('bi-eye-slash');
        });

    </script>
{% endblock %}

website/templates/admin_manage_game.html
{% extends 'admin_base_top_nav.html' %}

{% block title %}
    MANAGE EVENT
{% endblock %}

{% block content %}

<div>
    <!-- jinjacode flash message form flask-->
    {% with messages = get_flashed_messages(with_categories=true)%}
        {%if messages%}
            {%for category, message in messages%}
            <!-- sweet alert error-->
                {%if category =='manage_games_error'%}
                    <div id="myAlert" class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="close" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                <!-- sweet alert success-->
                {% else %}
                    <div id="myAlert" class="alert alert-success alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="close" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>

<div class="container mt-5">
    <h1>Add GAME:</h1>
    <form method="POST">
        <div class="mb-3">
            <label for="gamename" class="form-label">Game Name</label>
            <input type="text" class="form-control" id="gamename" name="gamename" required>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary"><i class="fas fa-plus"> ADD</i></button>
        </div>
    </form>
</div>

<div class="container mt-5">
    <h1><i class="fas fa-trophy"></i>All GAMES:</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Game Titles</th>
                <th>Links</th>
                <th><i class="fas fa-cog"> Options</i></th>
            </tr
        </thead>
        <tbody>
            {% for game in games %}
            <tr>
                <td><i class="fas fa-compact-disc"> {{ game.game_name }}</i> </td>
                <td><a href="{{ url_for('admin_views.add_links', game_id=game.id) }}"> <i class="fas fa-link">Links</i> </td>

                <td>
                    <form method="POST" action="/delete_game/{{ game.id }}">
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete {{game.game_name}}?')"><i class="fas fa-trash-alt"> Delete</i></button>
                    </form>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updateGameModal" onclick="showUpdateDialog('{{ game.id }}', '{{ game.game_name }}')"><i class="fas fa-edit"> Update</i></button>
                </td>

            </tr>
            {% endfor %}
        </tbody>
        
    </table>
</div>

<!-- Add this modal dialog at the end of your template -->
<div class="modal fade" id="updateGameModal" tabindex="-1" aria-labelledby="updateGameModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateGameModalLabel">Update Game</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="updateGameForm" method="POST">
                    <div class="mb-3">
                        <label for="updateGameName" class="form-label">New Game Name</label>
                        <input type="text" class="form-control" id="updateGameName" name="updateGameName" required>
                    </div>
                    <input type="hidden" id="updateGameId" name="updateGameId">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="updateGame()">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    //SWEET alert
    document.addEventListener('DOMContentLoaded', function () {
        var closeButton = document.querySelector('#myAlert .close');
        if (closeButton) {
            closeButton.addEventListener('click', function () {
                var alert = document.querySelector('#myAlert');
                if (alert) {
                    alert.remove();
                }
            });
        }
    });
    
    //update dialogbox
    function showUpdateDialog(gameId, gameName) {
        document.getElementById('updateGameId').value = gameId;
        document.getElementById('updateGameName').value = gameName;
    }

    function updateGame() {
        var gameId = document.getElementById('updateGameId').value;
        var newGameName = document.getElementById('updateGameName').value;

        if (!newGameName.trim()) {
            alert('Please enter a non-empty game name');
            return;
        }

        $.ajax({
            type: 'POST',
            url: '/update_game',
            data: {
                updateGameId: gameId,
                updateGameName: newGameName
            },
            success: function(response) {
                alert('Game updated successfully');
                window.location.reload();
            },
            error: function(xhr, status, error) {
                var errorMessage = '';
                if (xhr.responseJSON && xhr.responseJSON.error) {
                    errorMessage = xhr.responseJSON.error;
                } else {
                    errorMessage = 'An error occurred while updating the game';
                }
                alert(errorMessage);
            }
        });

        var updateGameModal = bootstrap.Modal.getInstance(document.getElementById('updateGameModal'));
        updateGameModal.hide();
    }
</script>
{% endblock %}

website/templates/admin_manage_link.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>          
    {% block title %}

    {% endblock %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>

    <div>
        <!-- jinjacode flash message form flask-->
        {% with messages = get_flashed_messages(with_categories=true)%}
            {%if messages%}
                {%for category, message in messages%}
                <!-- sweet alert error-->
                    {%if category =='manage_links_error'%}
                        <div id="myAlert" class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{message}}
                            <button type="button" class="close" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    <!-- sweet alert success-->
                    {% else %}
                        <div id="myAlert" class="alert alert-success alert-dismissible fade show" role="alert">
                            {{message}}
                            <button type="button" class="close" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand"><h1>GAME LINKS</h1></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin_views.add_games') }}"><h1>&#8630;</h1></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

<div class="container mt-3">
    <h1>Add Link:</h1>
    <form method="POST">
        <div class="mb-3">
            <label for="link" class="form-label">LINK</label>
            <input type="url" class="form-control" id="link" name="link" pattern="https?://.+" title="Include http:// or https:// in the URL" required>
        </div>
        <button type="submit" class="btn btn-primary"><i class="fas fa-plus"> ADD</i></button>

    </form>
</div>
<div class="container mt-3">
    <h1>LINKS for <i class="fas fa-compact-disc"> {{ game.game_name }}</i></h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>LINKS</th>
                <th><i class="fas fa-cog"> Options</i></th>
            </tr>
        </thead>
        <tbody>
            {% for link in links %}
            <tr>
                <td><i class="fas fa-link"></i> {{ link.url }}</td>
                <td>
                    <form method="POST" action="{{ url_for('admin_views.delete_links', link_id=link.id) }}">
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fas fa-trash-alt"> Delete</i></button>
                    </form>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updateLinkModal{{ link.id }}" onclick="showUpdateDialog('{{ link.id }}', '{{ link.url }}')"><i class="fas fa-edit"> Update</i></button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
        </tfoot>
    </table>
</div>

<!-- Update Link Modals -->
{% for link in links %}
<div class="modal fade" id="updateLinkModal{{ link.id }}" tabindex="-1" aria-labelledby="updateLinkModalLabel{{ link.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateLinkModalLabel{{ link.id }}">Update Link</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="updateLinkForm{{ link.id }}" method="POST">
                    <div class="mb-3">
                        <label for="updateLink{{ link.id }}" class="form-label">New Link</label>
                        <input type="url" class="form-control" id="updateLink{{ link.id }}" name="updateLink" pattern="https?://.+" title="Include http:// or https:// in the URL" required>
                    </div>
                    <input type="hidden" id="updateLinkId{{ link.id }}" name="updateLinkId" value="{{ link.id }}">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fas fa-times"> Close</i></button>
                <button type="button" class="btn btn-primary" onclick="updateLink('{{ link.id }}')"><i class="fas fa-save"> Save Changes</i></button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>
    //SWEET alert
    document.addEventListener('DOMContentLoaded', function () {
        var closeButton = document.querySelector('#myAlert .close');
        if (closeButton) {
            closeButton.addEventListener('click', function () {
                var alert = document.querySelector('#myAlert');
                if (alert) {
                    alert.remove();
                }
            });
        }
    });

   // Show update link modal and fill in existing link data
    function showUpdateDialog(linkId, linkUrl) {
        document.getElementById('updateLink' + linkId).value = linkUrl;
    }

    // Update link function
    function updateLink(linkId) {
        var newLinkUrl = document.getElementById('updateLink' + linkId).value;

        if (!newLinkUrl.trim().startsWith('http://') && !newLinkUrl.trim().startsWith('https://')) {
            alert('URL must start with http:// or https://');
            return;
        }

        // Perform AJAX request to update the link
        $.ajax({
            type: 'POST',
            url: '/update_link/' + linkId,
            data: {
                updateLink: newLinkUrl
            },
            success: function(response) {
                alert('Link updated successfully');
                window.location.reload();
            },
            error: function(xhr, status, error) {
                var errorMessage = '';
                if (xhr.responseJSON && xhr.responseJSON.error) {
                    errorMessage = xhr.responseJSON.error;
                } else {
                    errorMessage = 'An error occurred while updating the game';
                }
                alert(errorMessage);
            }
        });

        // Close the modal
        var updateLinkModal = new bootstrap.Modal(document.getElementById('updateLinkModal' + linkId));
        updateLinkModal.hide();
    }


</script>
</body>

website/templates/public_base_top_nav.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    
</head>

<body>
    <nav id="pub_nav" class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <h7><b>ION-3DS</b></h7> <img src="https://cdn-icons-png.flaticon.com/128/1815/1815480.png" style="height: 1em; vertical-align: middle;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('public_views.about') }}">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">More</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('admin_auth.admin_login') }}">ADMIN-Login</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
  <!-- Main content -->
    {% block content %}

    {% endblock %}
  <!-- Bootstrap JS (Optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <style>
        #pub_nav.navbar {
            background-color: #a81b51 !important;
        }
        
        </style>

</body>

</html>